// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[Table("Branch")]
public partial class Branch
{
    [Key]
    public int BranchID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string BranchName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<IntakeBranchTrackUser> IntakeBranchTrackUsers { get; set; } = new List<IntakeBranchTrackUser>();

    [InverseProperty("Branch")]
    public virtual ICollection<PublishedExam> PublishedExams { get; set; } = new List<PublishedExam>();
}