// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

public partial class Exam
{
    [Key]
    public int ExamID { get; set; }

    public int? CourseID { get; set; }

    [StringLength(50)]
    public string ExamType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExamDate { get; set; }

    public int MCQQuestionCount { get; set; }

    public int TrueFalseQuestionCount { get; set; }

    public int Duration { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<PublishedExam> PublishedExams { get; set; } = new List<PublishedExam>();

    [InverseProperty("Exam")]
    public virtual ICollection<UserExam> UserExams { get; set; } = new List<UserExam>();

    [ForeignKey("ExamID")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}