// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class get_courses_with_student_countResult
    {
        public int courseid { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        public int? student_count { get; set; }
    }
}
