// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetAllQuestionsResult
    {
        public int QuestionID { get; set; }
        public int TopicID { get; set; }
        [StringLength(2147483647)]
        public string QuestionText { get; set; }
        [StringLength(20)]
        public string QuestionType { get; set; }
        [Column("Grade", TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
    }
}
