// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetAll_Student_ByCourseIDResult
    {
        public int UserID { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(255)]
        public string PasswordHash { get; set; }
        public DateTime? RegistrationDate { get; set; }
        [StringLength(255)]
        public string ProfileImagePath { get; set; }
    }
}
