// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetBranchByIDResult
    {
        public int BranchID { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(255)]
        public string Address { get; set; }
    }
}
