// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetCourseTopicsResult
    {
        public int TopicID { get; set; }
        [StringLength(255)]
        public string TopicName { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
    }
}
