// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetExamQuestionsAndChoicesResult
    {
        public int QuestionID { get; set; }
        [StringLength(2147483647)]
        public string QuestionText { get; set; }
        [StringLength(20)]
        public string QuestionType { get; set; }
        public int? ChoiceID { get; set; }
        [StringLength(2147483647)]
        public string ChoiceText { get; set; }
        public int? CorrectChoice { get; set; }
        public int? ChoiceOrder { get; set; }
    }
}
