// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetExamStudentAnswersResult
    {
        public int QuestionID { get; set; }
        [StringLength(2147483647)]
        public string QuestionText { get; set; }
        [StringLength(20)]
        public string QuestionType { get; set; }
        [StringLength(2147483647)]
        public string StudentAnswerText { get; set; }
        [StringLength(2147483647)]
        public string CorrectAnswer { get; set; }
        [Column("StudentScore", TypeName = "decimal(5,2)")]
        public decimal? StudentScore { get; set; }
    }
}
