// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetIntakeBranchTrackUsersResult
    {
        public int IntakeID { get; set; }
        public int BranchID { get; set; }
        public int TrackID { get; set; }
        public int UserID { get; set; }
    }
}
