// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI.ExamSystem.Models
{
    public partial class GetStudentsByDepartmentResult
    {
        public int UserID { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public DateTime? RegistrationDate { get; set; }
        [StringLength(100)]
        public string TrackName { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(10)]
        public string IntakeName { get; set; }
    }
}
