// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[Table("Intake")]
[Index("IntakeName", Name = "UQ__Intake__DFAC2D0BA41CD50E", IsUnique = true)]
public partial class Intake
{
    [Key]
    public int IntakeID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string IntakeName { get; set; }

    [InverseProperty("Intake")]
    public virtual ICollection<IntakeBranchTrackUser> IntakeBranchTrackUsers { get; set; } = new List<IntakeBranchTrackUser>();

    [InverseProperty("Intake")]
    public virtual ICollection<PublishedExam> PublishedExams { get; set; } = new List<PublishedExam>();
}