// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[PrimaryKey("IntakeID", "BranchID", "TrackID", "UserID")]
public partial class IntakeBranchTrackUser
{
    [Key]
    public int IntakeID { get; set; }

    [Key]
    public int BranchID { get; set; }

    [Key]
    public int TrackID { get; set; }

    [Key]
    public int UserID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("IntakeBranchTrackUsers")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("IntakeID")]
    [InverseProperty("IntakeBranchTrackUsers")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("TrackID")]
    [InverseProperty("IntakeBranchTrackUsers")]
    public virtual Track Track { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("IntakeBranchTrackUsers")]
    public virtual User User { get; set; }
}