// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

public partial class PublishedExam
{
    [Key]
    public int PublishedExamID { get; set; }

    public int ExamID { get; set; }

    public int BranchID { get; set; }

    public int TrackID { get; set; }

    public int IntakeID { get; set; }

    public int? CourseID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("PublishedExams")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("PublishedExams")]
    public virtual Course Course { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("PublishedExams")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("IntakeID")]
    [InverseProperty("PublishedExams")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("TrackID")]
    [InverseProperty("PublishedExams")]
    public virtual Track Track { get; set; }
}