// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[Table("QuestionChoice")]
public partial class QuestionChoice
{
    [Key]
    public int ChoiceID { get; set; }

    public int QuestionID { get; set; }

    [Required]
    public string ChoiceText { get; set; }

    public int CorrectChoice { get; set; }

    public int? ChoiceOrder { get; set; }

    [ForeignKey("QuestionID")]
    [InverseProperty("QuestionChoices")]
    public virtual Question Question { get; set; }
}