// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

public partial class Question
{
    [Key]
    public int QuestionID { get; set; }

    public int TopicID { get; set; }

    [Required]
    public string QuestionText { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string QuestionType { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Grade { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<QuestionChoice> QuestionChoices { get; set; } = new List<QuestionChoice>();

    [ForeignKey("TopicID")]
    [InverseProperty("Questions")]
    public virtual Topic Topic { get; set; }

    [ForeignKey("QuestionID")]
    [InverseProperty("Questions")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}