// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

public partial class Topic
{
    [Key]
    public int TopicID { get; set; }

    public int? CourseID { get; set; }

    [Required]
    [StringLength(255)]
    public string TopicName { get; set; }

    public string Description { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("Topics")]
    public virtual Course Course { get; set; }

    [InverseProperty("Topic")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}