// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[PrimaryKey("ExamID", "UserID")]
[Table("UserExam")]
public partial class UserExam
{
    [Key]
    public int ExamID { get; set; }

    [Key]
    public int UserID { get; set; }

    public int Grade { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("UserExams")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserExams")]
    public virtual User User { get; set; }
}