// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[Index("Email", Name = "UQ__Users__A9D10534146454C2", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    
    [StringLength(100)]
<<<<<<< HEAD
    [EmailAddress]
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        ErrorMessage = "Invalid email address format.")]
=======
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        ErrorMessage = "Invalid email address format.")]
>>>>>>> b55935cab961458162d19edb69aa80db6040757e
    public string Email { get; set; }

    [Required]
    [StringLength(255)]

    public string PasswordHash { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RegistrationDate { get; set; }

    [StringLength(255)]
    public string ProfileImagePath { get; set; }

    public bool IsDeleted { get; set; } = false;

    [InverseProperty("User")]
    public virtual ICollection<IntakeBranchTrackUser> IntakeBranchTrackUsers { get; set; } = new List<IntakeBranchTrackUser>();

    [InverseProperty("User")]
    public virtual ICollection<UserExam> UserExams { get; set; } = new List<UserExam>();

    [ForeignKey("UserID")]
    [InverseProperty("Users")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("UserID")]
    [InverseProperty("Users")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}