// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI.ExamSystem.Models;

[Index("Email", Name = "UQ__Users__A9D10534146454C2", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RegistrationDate { get; set; }


    public string? ProfileImagePath { get; set; }

    [StringLength(255)]
   

    [InverseProperty("User")]
    public virtual ICollection<IntakeBranchTrackUser> IntakeBranchTrackUsers { get; set; } = new List<IntakeBranchTrackUser>();

    [InverseProperty("User")]
    public virtual ICollection<UserExam> UserExams { get; set; } = new List<UserExam>();

    [ForeignKey("UserID")]
    [InverseProperty("Users")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("UserID")]
    [InverseProperty("Users")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}